// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package auditwatch

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type auditwatchEvent struct {
	CgroupId uint64
	Pid      uint32
	Path     [512]uint8
	_        [4]byte
}

// loadAuditwatch returns the embedded CollectionSpec for auditwatch.
func loadAuditwatch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AuditwatchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load auditwatch: %w", err)
	}

	return spec, err
}

// loadAuditwatchObjects loads auditwatch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*auditwatchObjects
//	*auditwatchPrograms
//	*auditwatchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAuditwatchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAuditwatch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// auditwatchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditwatchSpecs struct {
	auditwatchProgramSpecs
	auditwatchMapSpecs
	auditwatchVariableSpecs
}

// auditwatchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditwatchProgramSpecs struct {
	CommonLsmAudit *ebpf.ProgramSpec `ebpf:"common_lsm_audit"`
}

// auditwatchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditwatchMapSpecs struct {
	ApparmorDenials   *ebpf.MapSpec `ebpf:"apparmor_denials"`
	RegisteredCgroups *ebpf.MapSpec `ebpf:"registered_cgroups"`
}

// auditwatchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditwatchVariableSpecs struct {
}

// auditwatchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAuditwatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditwatchObjects struct {
	auditwatchPrograms
	auditwatchMaps
	auditwatchVariables
}

func (o *auditwatchObjects) Close() error {
	return _AuditwatchClose(
		&o.auditwatchPrograms,
		&o.auditwatchMaps,
	)
}

// auditwatchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAuditwatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditwatchMaps struct {
	ApparmorDenials   *ebpf.Map `ebpf:"apparmor_denials"`
	RegisteredCgroups *ebpf.Map `ebpf:"registered_cgroups"`
}

func (m *auditwatchMaps) Close() error {
	return _AuditwatchClose(
		m.ApparmorDenials,
		m.RegisteredCgroups,
	)
}

// auditwatchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAuditwatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditwatchVariables struct {
}

// auditwatchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAuditwatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditwatchPrograms struct {
	CommonLsmAudit *ebpf.Program `ebpf:"common_lsm_audit"`
}

func (p *auditwatchPrograms) Close() error {
	return _AuditwatchClose(
		p.CommonLsmAudit,
	)
}

func _AuditwatchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed auditwatch_x86_bpfel.o
var _AuditwatchBytes []byte
